blank_issues_enabled: false
contact_links:
  - name: Dot''s Twitter
    url: https://x.com/@anekodot
    about: @anekodot''s Twitter
    about: |
      For Velocity-related issues, please report these to Velocity themselves.
